apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayodeji-deployment
  labels: 
    app: my-app
    type: fronting
spec:
  selector: 
    matchLabels:
      type: front-end
  replicas: 6
  template: 
    metadata:
      name: ayodeji-locally-sourced
      labels:
        type: front-end
    spec:
      containers:
      - name: myapp
        image: deji_image:env
        imagePullPolicy: Never
        env:
          - name: FIRST_NAME
            valueFrom:
              secretKeyRef:
                name: ayo-secret-test
                key: first_name
          - name: LAST_NAME
            valueFrom:
              secretKeyRef:
                name: ayo-secret-test
                key: last_name
