apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayodeji-deployment
  labels: 
    app: my-app
    type: fronting
spec:
  selector: 
    matchLabels:
      type: front-end
  replicas: 6
  template: 
    metadata:
      name: ayo-pod
      labels:
        type: front-end
    spec:
      containers:
        - name: myapp
          image: deji_image:env
          imagePullPolicy: Never
