apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk-deployment
  labels: 
    app: my-app
    type: fronting
spec:
  selector: 
    matchLabels:
      type: front-end
  replicas: 3
  template: 
    metadata:
      name: ayo-pod
      labels:
        type: front-end
    spec:
      containers:
        - name: myapp
          image: nginx:1.18-perl 
          imagePullPolicy: IfNotPresent
