apiVersion: v1 
kind: Service
metadata:
  name: kodekloud-nodeport-service
spec:
  type: NodePort
  ports: 
    - targetPort: 80
      port: 80
      nodePort: 30002
  selector: 
    type: web-server
