apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "ayo-external-secret"
spec:
  refreshInterval: "1m"
  target:
    name: final-secret
    creationPolicy: 'Owner'
  dataFrom:
  - extract:
      key: first_and_last_key
      
      path: path-to-filter
          source: "exp-(.*?)-ression"
          target: "rewriting-$1-with-groups"
      name:
        regexp: ".*foobar.*"
      tags:
        foo: bar
      conversionStrategy: Unicode
      decodingStrategy: Base64
    rewrite:
    - regexp:
        source: "foo"
        target: "bar"
    - regexp:

status:
  # refreshTime is the time and date the external secret was fetched and
  # the target secret updated
  refreshTime: "2019-08-12T12:33:02Z"
  # Standard condition schema
  conditions:
  # ExternalSecret ready condition indicates the secret is ready for use.
  # This is defined as:
  # - The target secret exists
  # - The target secret has been refreshed within the last refreshInterval
  # - The target secret content is up-to-date based on any target templates
  - type: Ready
    status: "True" # False if last refresh was not successful
    reason: "SecretSynced"
    message: "Secret was synced"
    lastTransitionTime: "2019-08-12T12:33:02Z"
