apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "ayo-external-secret"
spec:
  refreshInterval: "1m"
  secretStoreRef: 
    name: ayo-secret-store
    type: SecretStore
  target:
    name: final-secret
    creationPolicy: 'Owner'
  dataFrom:
  - extract:
      key: first_and_last_key
