apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "ayo-external-secret"
spec:
  refreshInterval: "1m"
  target:
    name: final-secret
    creationPolicy: 'Owner'
  dataFrom:
  - extract:
      key: first_and_last_key
     

    message: "Secret was synced"
    lastTransitionTime: "2019-08-12T12:33:02Z"
